#!/bin/bash
# Thanks to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in for this
project_root=$( cd "$( dirname "$0" )/../" && pwd )

cd $project_root

$project_root/script/start_god
bundle exec rails s

