#!/bin/bash
# Thanks to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in for this
project_root=$( cd "$( dirname "$0" )/../" && pwd )

cd $project_root

kill_string="kill"
if [ -e "$project_root/vendor/mongoDB/bin/mongod" ]; then
  $project_root/vendor/mongoDB/bin/mongod --dbpath $project_root/db &
  kill_string="$kill_string $!"
fi
if [ -e "$project_root/vendor/redis-stable/src/redis-server" ]; then
  $project_root/vendor/redis-stable/src/redis-server &
  kill_string="$kill_string $!"
fi

bundle exec sidekiq -r $project_root -L $project_root/log/sidekiq.log &
kill_string="$kill_string $!"

trap "$kill_string" SIGINT SIGTERM
bundle exec rails s -e production 
