#!/bin/bash
# Thanks to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in for this
project_root=$( cd "$( dirname "$0" )/../" && pwd )

cd $project_root

kill_string=""
if [ -e "$project_root/vendor/mongoDB/bin/mongod" ]; then
  "$project_root/vendor/mongoDB/bin/mongod" --dbpath $project_root/db &
else
  mongod --dbpath $project_root/db &
fi
kill_string="$! $kill_string"

sleep 0.1

if [ -e "$project_root/vendor/redis-stable/src/redis-server" ]; then
  $project_root/vendor/redis-stable/src/redis-server &
  kill_string="$! $kill_string"
fi
sleep 0.1

sidekiq_timeout=1
bundle exec sidekiq -r $project_root -L $project_root/log/sidekiq.log -t $sidekiq_timeout &
sidekiq_pid="$!"

cd realtime
node . &
kill_string="$! $kill_string"

cd ..

trap "kill $kill_string; kill -TERM $sidekiq_pid; sleep $sidekiq_timeout; kill -KILL $sidekiq_pid" SIGINT SIGTERM
bundle exec rails s
