#!/bin/bash
# Thanks to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in for this
project_root=$( cd "$( dirname "$0" )/../" && pwd )

cd $project_root

$project_root/vendor/mongoDB/bin/mongod --dbpath $project_root/db &
pid[0]=$!
$project_root/vendor/redis-stable/src/redis-server &
pid[1]=$!
bundle exec sidekiq -r $project_root &
pid[2]=$!

trap "kill ${pid[2]} ${pid[1]} ${pid[0]}" SIGINT SIGTERM
bundle exec rails s
